---
name: Test
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['24.3', '25.2']
        elixir: ['1.13.4', '1.14.3']

    env:
      MIX_ENV: test

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Check out source
        uses: actions/checkout@v3

      - name: Install Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          rebar3-version: '3.18.0'

      - name: Retrieve cached deps
        uses: actions/cache@v3
        with:
          path: |
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir}}-${{ hashFiles('**/rebar.lock') }}
          restore-keys: |
            ${{ matrix.otp }}-${{ matrix.elixir }}-

      - name: Check formatting
        run: rebar3 steamroll --check

      - name: Run Erlang tests
        run: rebar3 ct

      - name: Install Elixir tools
        working-directory: mix_tests
        run: mix do local.rebar --force, local.hex --force

      - name: Get Elixir deps
        working-directory: mix_tests
        run: mix deps.get

      - name: Run Elixir tests
        working-directory: mix_tests
        run: mix test

      - name: Run static code analysis checks
        run: rebar3 dialyzer
