on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.4"

      - run: rebar3 eunit

      # - run: mix deps.get
      #   working-directory: mix_tests

      # - run: mix test
      #   working-directory: mix_tests
