---
name: Test
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24.2', '25.0']
        elixir: ['1.13.4', '1.14.0']

    env:
      MIX_ENV: test

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        with:
          path: |
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Check formatting
        run: rebar3 steamroll --check

      - name: Run Erlang tests
        run: rebar3 ct

      - name: Install Elixir test dependencies
        working-directory: mix_tests
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Run Elixir tests
        working-directory: mix_tests
        run: mix test

      - name: Run static code analysis checks
        run: |
          rebar3 dialyzer
